// examples/svelte-example/src/lib/TaskList.svelte
<script>
  import TaskItem from './TaskItem.svelte';

  let { tasks, onSetComplete, onRemove, onViewDetails } = $props();
</script>

<div class="task-list">
  {#if tasks.length === 0}
    <div class="empty-state">
      <p>No tasks found. Add some tasks to get started!</p>
    </div>
  {:else}
    {#each tasks as task (task.id)}
      <TaskItem
        {task}
        onSetComplete={(completed) => onSetComplete(task.id, completed)}
        onRemove={() => onRemove(task.id)}
        onViewDetails={() => onViewDetails(task)}
      />
    {/each}
  {/if}
</div>

<style>
  .task-list {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }

  .empty-state {
    text-align: center;
    padding: 3rem 1rem;
    color: #6b7280;
  }

  .empty-state p {
    font-size: 1.1rem;
    margin: 0;
  }
</style>

// examples/react-example/src/components/TaskList.js
import React from 'react';
import TaskItem from './TaskItem';

const TaskList = ({ tasks, onSetComplete, onRemove, onViewDetails }) => {
  if (tasks.length === 0) {
    return (
      <div className="task-list">
        <div className="empty-state">
          <p>No tasks found. Add some tasks to get started!</p>
        </div>
      </div>
    );
  }

  return (
    <div className="task-list">
      {tasks.map(task => (
        <TaskItem
          key={task.id}
          task={task}
          onSetComplete={(completed) => onSetComplete(task.id, completed)}
          onRemove={() => onRemove(task.id)}
          onViewDetails={() => onViewDetails(task)}
        />
      ))}
    </div>
  );
};

export default TaskList;
