// examples/vue-example/src/components/TaskDetailsModal.vue
<script setup>
import { defineProps, defineEmits, ref, watch } from 'vue';

const props = defineProps({
    task: Object,
    show: Boolean
});

const emit = defineEmits(['close', 'update']);

const editedTask = ref({ ...props.task });

// Reset form when task changes
watch(() => props.task, (newTask) => {
    if (newTask) {
        editedTask.value = { ...newTask };
    }
}, { deep: true });

function handleSave() {
    emit('update', { ...editedTask.value });
    emit('close');
}

function handleToolUpdateDetails(event) {
    const { text, dueDate, priority, notes } = event.detail;
    const updates = { ...editedTask.value };

    if (text !== undefined) updates.text = text;
    if (dueDate !== undefined) updates.dueDate = dueDate;
    if (priority !== undefined) updates.priority = priority;
    if (notes !== undefined) updates.notes = notes;

    editedTask.value = updates;
    handleSave();
}

function setText(event) {
    const text = event.detail.text;
    editedTask.value.text = text;
}

function setDueDate(event) {
    const dueDate = event.detail.dueDate;
    editedTask.value.dueDate = dueDate;
}

function setPriority(event) {
    const priority = event.detail.priority;
    editedTask.value.priority = priority;
}

function setNotes(event) {
    const notes = event.detail.notes;
    editedTask.value.notes = notes;
}
</script>

<template>
    <div v-if="show && task" class="modal-overlay" @click="emit('close')">
        <div class="modal-content" @click.stop>
            <div class="modal-header">
                <h2>Task Details</h2>
                <button class="close-button" @click="emit('close')">&times;</button>
            </div>

            <form @submit.prevent="handleSave" class="task-form">
                <div class="form-group">
                    <label for="task-text">Task</label>
                    <input id="task-text" v-model="editedTask.text" type="text" required class="form-control" />
                </div>

                <div class="form-group">
                    <label for="due-date">Due Date (Optional)</label>
                    <input id="due-date" v-model="editedTask.dueDate" type="date" class="form-control" />
                </div>

                <div class="form-group">
                    <label for="priority">Priority</label>
                    <select id="priority" v-model="editedTask.priority" class="form-control">
                        <option value="low">Low</option>
                        <option value="medium">Medium</option>
                        <option value="high">High</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="notes">Notes</label>
                    <textarea id="notes" v-model="editedTask.notes" rows="3" class="form-control"></textarea>
                </div>

                <div class="button-group">
                    <button type="button" @click="emit('close')" class="btn-cancel">Cancel</button>
                    <button type="submit" class="btn-save">Save Changes</button>
                </div>
            </form>

            <context name="current_task">
                You are currently editing the task with ID {{ task.id }}:
                - text: {{ task.text }}
                - due date: {{ task.dueDate || 'none' }}
                - priority: {{ task.priority || 'medium' }}
                - notes: {{ task.notes || 'none' }}
            </context>

            <tool name="set_text" description="Set the text of the current task" @call="setText">
                <prop name="text" type="string" :description="`New text for task (currently: ${editedTask.text})`">{{
                    editedTask.text }}</prop>
            </tool>

            <tool name="set_due_date" description="Set the due date of the current task" @call="setDueDate">
                <prop name="dueDate" type="string"
                    :description="`Due date in YYYY-MM-DD format (currently: ${editedTask.dueDate || 'none'})`">{{
                        editedTask.dueDate || '' }}</prop>
            </tool>

            <tool name="set_priority" description="Set the priority of the current task" @call="setPriority">
                <prop name="priority" type="string"
                    :description="`Priority: low, medium, or high (currently: ${editedTask.priority || 'medium'})`">{{
                        editedTask.priority || 'medium' }}</prop>
            </tool>

            <tool name="set_notes" description="Set the notes for the current task" @call="setNotes">
                <prop name="notes" type="string"
                    :description="`Additional notes for the task (currently: ${editedTask.notes || 'none'})`">{{
                    editedTask.notes || '' }}</prop>
            </tool>
        </div>
    </div>
</template>

<style scoped>
.modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.5);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 100;
}

.modal-content {
    background-color: white;
    border-radius: 12px;
    width: 90%;
    max-width: 500px;
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15);
    overflow: hidden;
}

.modal-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1.25rem;
    background-color: #f9fafb;
    border-bottom: 1px solid #e5e7eb;
}

.modal-header h2 {
    margin: 0;
    font-size: 1.25rem;
    color: #111827;
}

.close-button {
    background: none;
    border: none;
    font-size: 1.5rem;
    cursor: pointer;
    color: #6b7280;
}

.task-form {
    padding: 1.5rem;
}

.form-group {
    margin-bottom: 1.25rem;
}

.form-group label {
    display: block;
    margin-bottom: 0.5rem;
    font-weight: 500;
    color: #374151;
}

.form-control {
    width: 100%;
    padding: 0.75rem;
    border: 1px solid #d1d5db;
    border-radius: 6px;
    font-size: 1rem;
}

.form-control:focus {
    outline: none;
    border-color: #a5b4fc;
    box-shadow: 0 0 0 3px rgba(165, 180, 252, 0.3);
}

textarea.form-control {
    resize: vertical;
}

.button-group {
    display: flex;
    justify-content: flex-end;
    gap: 0.75rem;
    margin-top: 1.5rem;
}

.btn-cancel {
    padding: 0.75rem 1.25rem;
    background-color: #f3f4f6;
    color: #374151;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-weight: 500;
}

.btn-save {
    padding: 0.75rem 1.25rem;
    background-color: #4f46e5;
    color: white;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-weight: 500;
}

.btn-save:hover {
    background-color: #4338ca;
}

.btn-cancel:hover {
    background-color: #e5e7eb;
}
</style>

// examples/svelte-example/src/lib/TaskDetailsModal.svelte
<script>
  let { task, onClose, onUpdate } = $props();
  
  // Create a local copy for editing
  let editedTask = $state({ ...task });
  
  function handleSubmit() {
    onUpdate(editedTask);
    onClose();
  }

  function handleSetText(event) {
    const { text } = event.detail || {};
    editedTask.text = text;
    
    // Send success response
    event.target.dispatchEvent(new CustomEvent('response', {
      detail: {
        success: true,
        result: { task_id: task.id, new_text: text },
        message: `Task text updated to "${text}"`
      }
    }));
  }

  function handleSetPriority(event) {
    const { priority } = event.detail || {};
    editedTask.priority = priority;
    
    // Send success response
    event.target.dispatchEvent(new CustomEvent('response', {
      detail: {
        success: true,
        result: { task_id: task.id, new_priority: priority },
        message: `Task priority updated to ${priority}`
      }
    }));
  }

  function handleSetDueDate(event) {
    const { due_date } = event.detail || {};
    editedTask.dueDate = due_date;
    
    // Send success response
    event.target.dispatchEvent(new CustomEvent('response', {
      detail: {
        success: true,
        result: { task_id: task.id, new_due_date: due_date },
        message: `Task due date updated to ${due_date || 'none'}`
      }
    }));
  }

  function handleSetNotes(event) {
    const { notes } = event.detail || {};
    editedTask.notes = notes;
    
    // Send success response
    event.target.dispatchEvent(new CustomEvent('response', {
      detail: {
        success: true,
        result: { task_id: task.id, new_notes: notes },
        message: 'Task notes updated successfully'
      }
    }));
  }

  function handleSaveChanges(event) {
    handleSubmit();
    
    // Send success response
    event.target.dispatchEvent(new CustomEvent('response', {
      detail: {
        success: true,
        result: { task_id: task.id, updated_task: editedTask },
        message: `All changes saved for task "${editedTask.text}"`
      }
    }));
  }

  // Close modal when clicking outside
  function handleBackdropClick(event) {
    if (event.target === event.currentTarget) {
      onClose();
    }
  }

  // Close modal on Escape key
  function handleKeydown(event) {
    if (event.key === 'Escape') {
      onClose();
    }
  }
</script>

<svelte:window onkeydown={handleKeydown} />

<div class="modal-backdrop" onclick={handleBackdropClick} role="dialog" aria-modal="true" tabindex="-1" onkeydown={(e) => e.key === 'Enter' && handleBackdropClick(e)}>
  <div class="modal-content">
    <div class="modal-header">
      <h2>Task Details</h2>
      <button onclick={onClose} class="close-button" title="Close">✕</button>
    </div>
    
    <form onsubmit={handleSubmit} class="modal-body">
      <div class="form-group">
        <label for="task-text">Task Text</label>
        <input
          id="task-text"
          type="text"
          bind:value={editedTask.text}
          class="form-input"
          required
        />
      </div>
      
      <div class="form-group">
        <label for="task-priority">Priority</label>
        <select
          id="task-priority"
          bind:value={editedTask.priority}
          class="form-select"
        >
          <option value="low">Low</option>
          <option value="medium">Medium</option>
          <option value="high">High</option>
        </select>
      </div>
      
      <div class="form-group">
        <label for="task-due-date">Due Date</label>
        <input
          id="task-due-date"
          type="date"
          bind:value={editedTask.dueDate}
          class="form-input"
        />
      </div>
      
      <div class="form-group">
        <label for="task-notes">Notes</label>
        <textarea
          id="task-notes"
          bind:value={editedTask.notes}
          class="form-textarea"
          rows="3"
          placeholder="Add any additional notes..."
        ></textarea>
      </div>
      
      <div class="form-group">
        <label class="checkbox-label">
          <input
            type="checkbox"
            bind:checked={editedTask.completed}
            class="form-checkbox"
          />
          Mark as completed
        </label>
      </div>
      
      <div class="modal-actions">
        <button type="button" onclick={onClose} class="cancel-button">
          Cancel
        </button>
        <button type="submit" class="save-button">
          Save Changes
        </button>
      </div>
    </form>

    <!-- VOIX Tools for task editing -->
    <tool
      name="set_text"
      description="Update the task text"
      oncall={handleSetText}
    >
      <prop name="text" type="string" description="New task text" required>
        {editedTask.text}
      </prop>
    </tool>

    <tool
      name="set_priority"
      description="Update the task priority"
      oncall={handleSetPriority}
    >
      <prop name="priority" type="string" description="New priority: low, medium, high" required>
        {editedTask.priority}
      </prop>
    </tool>

    <tool
      name="set_due_date"
      description="Update the task due date"
      oncall={handleSetDueDate}
    >
      <prop name="due_date" type="string" description="New due date in YYYY-MM-DD format">
        {editedTask.dueDate || '2025-06-15'}
      </prop>
    </tool>

    <tool
      name="set_notes"
      description="Update the task notes"
      oncall={handleSetNotes}
    >
      <prop name="notes" type="string" description="New task notes">
        {editedTask.notes || ''}
      </prop>
    </tool>

    <tool
      name="save_changes"
      description="Save all changes to the task"
      oncall={handleSaveChanges}
    >
    </tool>

    <!-- Context for the modal -->
    <context name="modal_state">
      Editing task: {editedTask.text}
      Current priority: {editedTask.priority}
      Current due date: {editedTask.dueDate || 'none'}
      Current status: {editedTask.completed ? 'completed' : 'incomplete'}
      Notes length: {editedTask.notes?.length || 0} characters
    </context>
  </div>
</div>

<style>
  .modal-backdrop {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000;
    padding: 1rem;
  }

  .modal-content {
    background: white;
    border-radius: 12px;
    width: 100%;
    max-width: 500px;
    max-height: 90vh;
    overflow-y: auto;
    box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
  }

  .modal-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1.5rem 1.5rem 1rem 1.5rem;
    border-bottom: 1px solid var(--border-color);
  }

  .modal-header h2 {
    margin: 0;
    font-size: 1.5rem;
    font-weight: 600;
    color: var(--text-color);
  }

  .close-button {
    width: 2rem;
    height: 2rem;
    border: none;
    background: #f3f4f6;
    border-radius: 6px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 1.25rem;
    color: #6b7280;
    transition: all 0.2s ease;
  }

  .close-button:hover {
    background: #e5e7eb;
    color: var(--text-color);
  }

  .modal-body {
    padding: 1.5rem;
  }

  .form-group {
    margin-bottom: 1.5rem;
  }

  .form-group:last-child {
    margin-bottom: 0;
  }

  .form-group label {
    display: block;
    margin-bottom: 0.5rem;
    font-weight: 500;
    color: var(--text-color);
  }

  .form-input,
  .form-select,
  .form-textarea {
    width: 100%;
    padding: 0.75rem;
    border: 1px solid var(--border-color);
    border-radius: 6px;
    font-size: 1rem;
    transition: border-color 0.2s ease;
    box-sizing: border-box;
  }

  .form-input:focus,
  .form-select:focus,
  .form-textarea:focus {
    outline: none;
    border-color: var(--primary-color);
    box-shadow: 0 0 0 3px rgba(79, 70, 229, 0.1);
  }

  .form-textarea {
    resize: vertical;
    min-height: 80px;
  }

  .checkbox-label {
    display: flex !important;
    align-items: center;
    gap: 0.5rem;
    cursor: pointer;
    margin-bottom: 0 !important;
  }

  .form-checkbox {
    width: auto !important;
    margin: 0;
  }

  .modal-actions {
    display: flex;
    gap: 1rem;
    justify-content: flex-end;
    margin-top: 2rem;
  }

  .cancel-button,
  .save-button {
    padding: 0.75rem 1.5rem;
    border-radius: 6px;
    font-size: 1rem;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .cancel-button {
    background: #f3f4f6;
    color: var(--text-color);
    border: 1px solid var(--border-color);
  }

  .cancel-button:hover {
    background: #e5e7eb;
  }

  .save-button {
    background: var(--primary-color);
    color: white;
    border: 1px solid var(--primary-color);
  }

  .save-button:hover {
    background: var(--primary-hover);
  }

  @media (max-width: 640px) {
    .modal-backdrop {
      padding: 0.5rem;
    }
    
    .modal-content {
      max-height: 95vh;
    }
    
    .modal-actions {
      flex-direction: column;
    }
  }
</style>
